# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## Common configuration
  config.vm.provision "common dummy",
                      type: "shell",
                      preserve_order: true,
                      path: "provision/default/01-dummy.sh"
  
  config.vm.provision "common hostname",
                      type: "shell",
                      preserve_order: true,
                      run: "always",
                      path: "provision/default/01-hostname.sh"
  
  config.vm.provision "common user",
                      type: "shell",
                      preserve_order: true,
                      path: "provision/default/01-user.sh"
  
  ## Server configuration
  config.vm.define "server", autostart: false do |server|
    server.vm.box = "rocky9"
    server.vm.hostname = 'server'

    server.vm.boot_timeout = 1440
    
    server.ssh.insert_key = false
    server.ssh.username = 'vagrant'
    server.ssh.password = 'vagrant'

    server.vm.network :private_network,
                      ip: "192.168.1.1",
                      virtualbox__intnet: true

    server.vm.provision "server dummy",
                        type: "shell",
                        preserve_order: true,
                        path: "provision/server/01-dummy.sh"

    server.vm.provision "server dns",
			type: "shell",
			preserve_order: true,
			path: "provision/server/dns.sh"

    server.vm.provision "server dhcp",
			type: "shell",
			preserve_order: true,
			path: "provision/server/dhcp.sh"

    server.vm.provision "server http",
			type: "shell",
			preserve_order: true,
			path: "provision/server/http.sh"

    server.vm.provision "server mysql",
			type: "shell",
			preserve_order: true,
			path: "provision/server/mysql.sh"

    server.vm.provision "server firewall",
			type: "shell",
			preserve_order: true,
			path: "provision/server/firewall.sh"

    server.vm.provision "server mail",
			type: "shell",
			preserve_order: true,
			path: "provision/server/mail.sh"

    server.vm.provision "server ssh",
			type: "shell",
			preserve_order: true,
			path: "provision/server/ssh.sh"

    server.vm.provision "server ntp",
			type: "shell",
			preserve_order: true,
			path: "provision/server/ntp.sh"
    server.vm.provision "server nfs",
			type: "shell",
			preserve_order: true,
			path: "provision/server/nfs.sh"
    server.vm.provision "SMB server",
			type: "shell",
			preserve_order: true,
			path: "provision/server/smb.sh"
    
    server.vm.provision "server netlog",
			type: "shell",
			preserve_order: true,
			path: "provision/server/netlog.sh"
    
    server.vm.provision "server protect",
			type: "shell",
			preserve_order: true,
			path: "provision/server/protect.sh"


    server.vm.provider :virtualbox do |v|
      v.linked_clone = true
      # Customize the amount of memory on the VM
      v.memory = 1024
      v.cpus = 1
      v.name = "server"
      # Display the VirtualBox GUI when booting the machine
      v.gui = true
      # Set the video memory to 12Mb
      v.customize ["modifyvm", :id, "--vram", "12"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end

  ## Client configuration
  config.vm.define "client", autostart: false do |client|
    client.vm.box = "rocky9"
    client.vm.hostname = 'client'
    
    client.vm.boot_timeout = 1440

    client.ssh.insert_key = false
    client.ssh.username = 'vagrant'
    client.ssh.password = 'vagrant'

    client.vm.network :private_network,
                      type: "dhcp",
                      virtualbox__intnet: true

    client.vm.provision "client dummy",
                        type: "shell",
                        preserve_order: true,
                        path: "provision/client/01-dummy.sh"

    client.vm.provision "client routing",
                        type: "shell",
                        preserve_order: true,
                        run: "always",
                        path: "provision/client/01-routing.sh"

    client.vm.provision "client mail",
			type: "shell",
			preserve_order: true,
			path: "provision/client/mail.sh"
   client.vm.provision "client ntp",
			type: "shell",
			preserve_order: true,
			path: "provision/client/ntp.sh"

   client.vm.provision "client nfs",
			type: "shell",
			preserve_order: true,
			path: "provision/client/nfs.sh"
   
   client.vm.provision "SMB client",
			type: "shell",
			preserve_order: true,
			path: "provision/client/smb.sh"
   client.vm.provision "client netlog",
			type: "shell",
			preserve_order: true,
			path: "provision/client/netlog.sh"

    client.vm.provider :virtualbox do |v|
      v.linked_clone = true
      # Customize the amount of memory on the VM
      v.memory = 1024
      v.cpus = 1
      v.name = "client"
      # Display the VirtualBox GUI when booting the machine
      v.gui = true
      # Set the video memory to 12Mb
      v.customize ["modifyvm", :id, "--vram", "12"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end
end
